### ISSUE TITLE
GeoJSON source URL doesn't change in fork builds

### ISSUE THREAD

**Issue by jacobwhall** [MapRVA/open-landmarks#2]
I forked this repository, and now I cannot use the included GitHub Action to preview changes before merging them upstream because `index.html` has the MapRVA repository hard-coded as a source. It would be nice if the build script fills in the repository name and owner into the source URL using environment variables, using MapRVA as a fallback.

**Comment by dschep** [comment]
fixed by ecdd9710abf0d1f05475b951b7caeb1ca9c09c1d
