### ISSUE TITLE
Support right-to-left text in landmark labels

### ISSUE THREAD

**Issue by jacobwhall** [MapRVA/open-landmarks#6]
The Great Pyramid of Giza easily qualifies as a landmark, I think. It's localized name is هرم خوفو. This text does not render on the embedded MapLibre map once deployed. I suspect we'll need to install [this MapLibre plugin](https://maplibre.org/maplibre-gl-js/docs/examples/mapbox-gl-rtl-text/).

This raises a larger question of how we should handle localization. I think Americana's solution of allowing the user to pick their preferred display language is really cool. I wonder how difficult it would be to borrow that code, or implement something similar.

**Comment by dschep** [comment]
root cause is actually the font being used, Overpass Ultra already was patched to use the plugin: https://gitlab.com/trailstash/overpass-ultra/-/issues/14

will push a fix soon
